apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-aggregator-service
  labels:
    app: data-aggregator-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-aggregator-service
  template:
    metadata:
      labels:
        app: data-aggregator-service
    spec:
      containers:
      - name: data-aggregator-service
        image: vishwanih/data-aggregator-service:latest
        ports:
        - containerPort: 5004
        envFrom:
        - configMapRef:
            name: healthsync-config
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: database_url
