apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-aggregator-service-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-aggregator-service
      version: green
  template:
    metadata:
      labels:
        app: data-aggregator-service
        version: green
    spec:
      containers:
      - name: data-aggregator-service
        image: vishwanih/data-aggregator-service:latest
        ports:
        - containerPort: 5004
