apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service
  labels:
    app: patient-record-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-record-service
  template:
    metadata:
      labels:
        app: patient-record-service
    spec:
      containers:
      - name: patient-record-service
        image: vishwanih/patient-service:latest
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: healthsync-config
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: database_url
