apiVersion: v1
kind: Service
metadata:
  name: data-aggregator-service-blue
spec:
  selector:
    app: data-aggregator-service
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5004
  type: ClusterIP
