apiVersion: v1
kind: Service
metadata:
  name: data-aggregator-service
spec:
  selector:
    app: data-aggregator-service
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5004
  type: LoadBalancer
