apiVersion: v1
kind: Service
metadata:
  name: data-aggregator-service
  labels:
    app: data-aggregator-service
spec:
  selector:
    app: data-aggregator-service
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5004

