apiVersion: v1
kind: Service
metadata:
  name: notification-service-blue
spec:
  selector:
    app: notification-service
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003
  type: ClusterIP
