apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003

