apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  selector:
    app: patient-record-service
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: LoadBalancer
