apiVersion: v1
kind: Service
metadata:
  name: patient-record-service-blue
spec:
  selector:
    app: patient-record-service
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: ClusterIP
