name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install dependencies for each service
    - name: Install Dependencies for Patient Record Service
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ./Patient_Record_Service/requirements.txt

    - name: Install Dependencies for Appointment Service
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ./Appointment_Service/requirements.txt

    - name: Install Dependencies for Notification Service
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ./Notification_Service/requirements.txt

    - name: Install Dependencies for Data Aggregator Service
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ./Data_Aggregator_Service/requirements.txt

    # Run tests for each service
   # - name: Run Tests for Patient Record Service
  #    run: python -m unittest discover -s ./Patient_Record_Service/tests

    - name: Run Tests for Appointment Service
      run: python -m unittest discover -s ./Appointment_Service/tests

    - name: Run Tests for Notification Service
      run: python -m unittest discover -s ./Notification_Service/tests

    - name: Run Tests for Data Aggregator Service
      run: python -m unittest discover -s ./Data_Aggregator_Service/tests

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker images for each service
    - name: Build and Push Patient Record Service Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/patient-record-service:latest ./Patient_Record_Service
        docker push ${{ secrets.DOCKER_USERNAME }}/patient-record-service:latest

    - name: Build and Push Appointment Service Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/appointment-service:latest ./Appointment_Service
        docker push ${{ secrets.DOCKER_USERNAME }}/appointment-service:latest

    - name: Build and Push Notification Service Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/notification-service:latest ./Notification_Service
        docker push ${{ secrets.DOCKER_USERNAME }}/notification-service:latest

    - name: Build and Push Data Aggregator Service Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/data-aggregator-service:latest ./Data_Aggregator_Service
        docker push ${{ secrets.DOCKER_USERNAME }}/data-aggregator-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_JSON }}" > kubeconfig.json
        export KUBECONFIG=kubeconfig.json

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployments
        kubectl apply -f kubernetes/services
